apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavenapp
  labels:
    app: mavenapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mavenapp
  template:
    metadata:
      labels:
        app: mavenapp
    spec:
      containers:
      - name: labmaven
        image: aditya8050/newimg2
        ports:
        - containerPort: 8080
